
### 로그인
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "user123",
  "password": "password123"
}


> {%
    client.test("Validate login response", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
        const authorization = response.headers.valueOf("Authorization");
        client.assert(authorization !== null, "Authorization header is missing");
        client.assert(authorization.startsWith("Bearer "), "Authorization header must start with Bearer ");
        const accessToken = authorization.substring("Bearer ".length);
        client.assert(accessToken.length > 0, "Access token is empty");
        client.global.set("accessToken", accessToken);
    });

%}