openapi: 3.0.0
info:
  title: Post API
  description: Post 관련 CRUD API
  version: 1.0.0
paths:
  /api/posts:
    get:
      summary: 모든 게시글 조회
      operationId: getAllPosts
      tags:
        - Post
      responses:
        '200':
          description: 게시글 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostResponse'
    post:
      summary: 게시글 생성
      operationId: createPost
      tags:
        - Post
      requestBody:
        description: 게시글 생성 요청
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
      responses:
        '200':
          description: 게시글 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
  /api/posts/{id}:
    get:
      summary: 게시글 조회
      operationId: getPostById
      tags:
        - Post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: 게시글 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
    put:
      summary: 게시글 수정
      operationId: updatePost
      tags:
        - Post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        description: 게시글 수정 요청
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
      responses:
        '200':
          description: 게시글 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
    delete:
      summary: 게시글 삭제
      operationId: deletePost
      tags:
        - Post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: 게시글 삭제 성공
components:
  schemas:
    PostRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        username:
          type: string
        password:
          type: string
      required:
        - title
        - content
        - username
        - password
    PostResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        username:
          type: string
