name: CI Pipeline

on:
  push:
    branches:
      - '*'
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy application.yml
        run: cp src/main/resources/application-sample.yml src/main/resources/application.yml

      - name: Create jwt.yml
        run: cp src/main/resources/jwt-sample.yml src/main/resources/jwt.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '8.10'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      # 성공 시 워크플로우 트리거 파일 생성
      - name: Trigger CD Workflow
        run: echo "trigger_cd=true" > trigger_cd.txt

      # Artifacts로 저장
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ci-artifacts
          path: trigger_cd.txt
