name: CI Pipeline

on:
  push:
    branches:
      - '*'
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # config copy => 추후 환경변수 & secret값으로 변경 예정
      - name: Copy application.yml
        run: cp src/main/resources/application-sample.yml src/main/resources/application.yml

      - name: Create jwt.yml
        run: cp src/main/resources/jwt-sample.yml src/main/resources/jwt.yml

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradle 설정
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '8.10'

      # 빌드
      - name: Build with Gradle
        run: ./gradlew build

      # 테스트
      - name: Run tests
        run: ./gradlew test

      # Docker 설치
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ ${{ secrets.APP_NAME }}:latest